hostcheckstop: Fix missing header
Fixes the following error:

 host_checkstop_obj.c: In function ‘is_host_booted’:
 host_checkstop_obj.c:46:10: error: implicit declaration of function
 ‘strcmp’ [-Werror=implicit-function-declaration]
      if ((strcmp(system_state, "HOST_BOOTED") == 0) ||

Signed-off-by: Joel Stanley <joel@jms.id.au>